import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    cardContainer: {
        width: '100%',
        minHeight: 300,
        alignSelf: 'stretch',
        borderRadius: 12,
        borderWidth: 5, 
        borderColor: '#FFE165', 
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 8,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 8,
        gap: 8,
        minHeight: 65,
    },
    pokemonName: {
        fontSize: 14,
        fontWeight: '900',
        color: '#111',
        textTransform: 'capitalize',
        flexShrink: 1,
        flexWrap: 'wrap',
        maxWidth: '100%',
    },
    pokemonId: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#333',
    },
    headerRight: {
        alignItems: 'flex-end',
        flexShrink: 1,
        minWidth: 0,
        minHeight: 50,
        justifyContent: 'flex-start',
    },
    hpText: {
        fontSize: 12,
        fontWeight: '900',
        color: '#D32F2F', 
        marginBottom: 6,
    },
    // Estilos dos botões modificados para suportar múltiplos botões lado a lado
    actionsContainer: {
        flexDirection: 'column',
        justifyContent: 'flex-end',
        gap: 4,
    },
    actionButton: {
        paddingHorizontal: 6,
        paddingVertical: 4,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#333',
        minWidth: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    evolveButton: {
        backgroundColor: '#FFF',
    },
    evolveButtonText: {
        fontSize: 9,
        fontWeight: '900',
        color: '#333',
        textTransform: 'uppercase',
    },
    devolveButton: {
        backgroundColor: '#EAEAEA', // Fundo cinza suave para diferenciar do evoluir
        borderColor: '#555',
    },
    devolveButtonText: {
        fontSize: 9,
        fontWeight: '900',
        color: '#555',
        textTransform: 'uppercase',
    },
    imageFrame: {
        backgroundColor: '#F8F8F8',
        width: '100%',
        height: 110,
        borderWidth: 4,
        borderColor: '#B0B0B0', 
        borderRadius: 2,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
        marginBottom: 12,
    },
    image: {
        width: 80,
        height: 80,
    },
    typesContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.9)',
        paddingVertical: 6,
        borderRadius: 20,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.1)',
    },
    typeText: {
        fontSize: 12,
        fontWeight: 'bold',
        textTransform: 'uppercase',
        color: '#333',
        marginHorizontal: 8,
    },
    attacksContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)', 
        borderRadius: 8,
        padding: 8,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.1)',
    },
    attackRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: '#EEE',
        paddingVertical: 6,
    },
    attackName: {
        fontSize: 12,
        fontWeight: 'bold',
        textTransform: 'capitalize',
        color: '#222',
    },
    attackDamage: {
        fontSize: 14,
        fontWeight: '900',
        color: '#111',
    }
});